const CONSTANTS = {
  RESPONSE_CODES: {
    SUCCESS: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
  },

  RESPONSE_MESSAGES: {
    SUCCESS: 'Success',
    BAD_REQUEST: 'Bad Request',
    UNAUTHORIZED: 'Unauthorized',
    FORBIDDEN: 'Forbidden',
    NOT_FOUND: 'Not Found',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
  },

  ERROR_MESSAGES: {
    VALIDATION_ERROR: 'Validation error',
    UNAUTHORIZED_ACCESS: 'Access is denied due to invalid credentials',
    RESOURCE_NOT_FOUND: 'The requested resource was not found',
    SERVER_ERROR: 'An unexpected error occurred on the server',
  },

  VALIDATION_MESSAGES: {
    INVALID_EMAIL: 'Email is not valid',
    INVALID_PASSWORD: 'Password is not valid',
    INVALID_NAME: 'Name is not valid',
    INVALID_PHONE: 'Phone is not valid',
    INVALID_ADDRESS: 'Address is not valid',
    INVALID_CITY: 'City is not valid',
    INVALID_STATE: 'State is not valid',
    INVALID_COUNTRY: 'Country is not valid',
    INVALID_ZIP: 'Zip is not valid',
    INVALID_ROLE: 'Role is not valid',
    INVALID_STATUS: 'Status is not valid',
    INVALID_ID: 'Id is not valid',
    INVALID_USER_ID: 'User Id is not valid',
    INVALID_CATEGORY_ID: 'Category Id is not valid',
    INVALID_PRODUCT_ID: 'Product Id is not valid',
    INVALID_ORDER_ID: 'Order Id is not valid',
    INVALID_ORDER_STATUS: 'Order Status is not valid',
    INVALID_ORDER_DATE: 'Order Date is not valid',
    INVALID_ORDER_AMOUNT: 'Order Amount is not valid',
    INVALID_ORDER_QUANTITY: 'Order Quantity is not valid',
    INVALID_ORDER_PRODUCT: 'Order Product is not valid',
    INVALID_ORDER_USER: 'Order User is not valid',
    INVALID_ORDER_ADDRESS: 'Order Address is not valid',
    INVALID_ORDER_PAYMENT: 'Order Payment is not valid',
    INVALID_ORDER_PAYMENT_TYPE: 'Order Payment Type is not valid',
    INVALID_ORDER_PAYMENT_STATUS: 'Order Payment Status is not valid',
    INVALID_ORDER_PAYMENT_DATE: 'Order Payment Date is not valid',
    INVALID_ORDER_PAYMENT_AMOUNT: 'Order Payment Amount is not valid',
    INVALID_ORDER_PAYMENT_USER: 'Order Payment User is not valid',
    INVALID_ORDER_PAYMENT_ADDRESS: 'Order Payment Address is not valid',
    INVALID_ORDER_PAYMENT_PRODUCT: 'Order Payment Product is not valid',
    INVALID_ORDER_PAYMENT_QUANTITY: 'Order Payment Quantity is not valid',
    INVALID_ORDER_PAYMENT_MODE: 'Order Payment Mode is not valid',
    INVALID_ORDER_PAYMENT_CARD: 'Order Payment Card is not valid',
    INVALID_ORDER_PAYMENT_CARD_NUMBER: 'Order Payment Card Number is not valid',
    INVALID_ORDER_PAYMENT_CARD_EXPIRY: 'Order Payment Card Expiry is not valid',
    INVALID_ORDER_PAYMENT_CARD_CVV: 'Order Payment Card CVV is not valid',
    INVALID_ORDER_PAYMENT_CARD_TYPE: 'Order Payment Card Type is not valid',
    INVALID_ORDER_PAYMENT_CARD_HOLDER: 'Order Payment Card Holder is not valid',
  },
};

module.exports = CONSTANTS;
